version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    environment:
      - IMAGE_LATEST: "livepeer/protocol:latest"
    steps:
      - checkout
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Build docker image
          command: |
            npm run docker:build
      - run:
          name: Run linting
          command: npm run docker:run:lint
      - run:
          name: Run unit tests
          command: npm run docker:run:test:coverage
      - run:
          name: Run integration tests
          command: npm run docker:run:test:integration
